rest:
  ssl: true
  host: demo.dspace.org
  port: 443
  nameSpace: /server

acessoAcademico:
  logotipo: 'dspace-logo.jpg'
  titulo: 'DSpace'
  subTitulo: 'Publicação online para testes e dissertações'